# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      clickhouse:
        image: clickhouse/clickhouse-server:latest
        ports:
          - 8123:8123
        options: >-
          --health-cmd "wget --spider -q localhost:8123 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Wait for ClickHouse
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:8123/ping; then break; fi
            echo "Waiting for ClickHouse..."
            sleep 1
          done

      - name: Create database
        run: |
          curl -sS -X POST 'http://localhost:8123' --data-binary "CREATE DATABASE IF NOT EXISTS test_db"

      - run: npm ci
      - run: npm test
      - run: npm run build
      

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
